<?php
/// Register - Login
@define( '_tieudedangky', 'Your account information is used to log system vào on the sites you have joined the website. So please save your password in a safe place.');
@define( '_dangkythanhvien', 'Sign up');
@define( '_tendn', 'User name');
@define( '_matkhau', 'password');
@define( '_hoten', 'Full Name');
@define( '_captcha', 'Security Code');
@define( '_notnull', 'Do not Be Blank');
@define( '_datontai', 'already exists');
@define( '_nhapsai', 'Enter Sai');
@define( '_nhap', 'Enter');
@define( '_tieude', 'Title');
@define( '_noidung', 'Content');
@define( '_chon', 'Select');
@define( '_sai', 'Sai');
@define( '_dangky', 'Registration');
@define( '_gui', 'Submit');
@define( '_moi', 'New');
@define( '_lamlai', 'How Come');
@define( '_doimatkhau', 'Change Password');
@define( '_dangnhap', 'Login');
@define( '_chuachon', 'Never Select');
@define( '_nhaplaimatkhau', 'Enter the password');
@define( '_nhaplai' , 'Returns');
@define( '_dienthoai', 'Telephone');
@define( '_ngaysinh', 'Born');
@define( '_batbuocnhap', 'Mandatory');
@define( '_diachi', 'Address');
@define( '_dinhdang', 'Format');
@define( '_chuacotaikhoan', 'If you do not have an account please xim');
@define( '_neuquenmatkhau', 'If you forget the password can get back at');
@define( '_quenmatkhau', 'Forgot Password');
@define( '_nhapmanhuhinh', 'Enter the code as shown');
@define( '_doinet', 'About myself');
@define( '_nhapmaildadangky', 'Please enter the email you used to sign up to receive instructions to change your password.');
@define( '_hon6kytu', 'length of more than 6 characters!');
@define( '_neuchuacotk', 'If you do not have an account please');
@define( '_laylaitai', 'Get the password at');
@define( '_day', 'Here');
@define( '_ghinholansau', 'Remember Me For The Times');
@define( '_thongtintk', 'Account Information');
@define( '_luuthaydoi', 'Save Changes');
@define( '_emailtrue', 'You Can Use Email Hey!');
@define( '_emailfalse', 'E-mail has been used! Please enter a different email!');
@define( '_usernamefalse', 'Username already in use! Please enter a different username!');
@define( '_captchafalse', 'Enter the security code wrong!');
@define( '_usernamenull', 'Username does not exist!');
@define( '_activefalse', 'Account not activated! Please Check mail and enter the activation code!');
@define( '_dangnhaptc', 'Login Success!');
@define( '_dangxuattc', 'Sign Out Success!');
@define( '_chuadangnhap', 'You are not logged!');
@define( '_doimkthanhcong', 'Change Password Success!');
@define( '_luudatafalse', 'Save Data Failed! Please, please try again');
@define( '_capnhattc', 'Update Success!');
@define( '_keycodefalse', 'false activation code! Or has expired');
@define( '_linkkeycodefalse', 'Sai path trigger!');
@define( '_kichhoattc', 'Congratulations, you have successfully activate your account!');
@define( '_nhapemaildk', 'Email registering!');
@define( '_khongtimthayemail', 'No matches found email!');
@define( '_guithanhcongkttk', 'Submit successfully! </ br> We sent one link to your e-mail to change your password! </ br> Please login email and password change!');
@define( '_loaitv', 'Type Members');
@define( '_linhvuckd', 'Business Activities');
@define( '_quocgia', 'National');
@define( '_khuvuc', 'Regional');

?>